/*
File generated by custom templates
Important: Do not modify this file. Edit the file BannerInfo.cs instead.
*/
#region using directives
using System;
#endregion

namespace Certify.Domain.Entities
{
    [Serializable]
    public abstract class BannerInfoBase : BaseEntity
    {
        #region Constructors
        protected BannerInfoBase()
        {
            this.IsActive = true;
        }
        #endregion
        #region Properties

        private Int32 _bannerId;
        public virtual Int32 BannerId
        {
            get => _bannerId;
            set => SetProperty(ref _bannerId, value);
        }

        private string _title;
        public virtual string Title
        {
            get => _title;
            set => SetProperty(ref _title, value);
        }

        private string _content;
        public virtual string Content
        {
            get => _content;
            set => SetProperty(ref _content, value);
        }

        private string _imageUrl;
        public virtual string ImageUrl
        {
            get => _imageUrl;
            set => SetProperty(ref _imageUrl, value);
        }

        private bool _isActive;
        public virtual bool IsActive
        {
            get => _isActive;
            set => SetProperty(ref _isActive, value);
        }

        private DateTime _displayFrom;
        public virtual DateTime DisplayFrom
        {
            get => _displayFrom;
            set => SetProperty(ref _displayFrom, value);
        }

        private DateTime _displayTo;
        public virtual DateTime DisplayTo
        {
            get => _displayTo;
            set => SetProperty(ref _displayTo, value);
        }

        private DateTime _createdOn;
        public virtual DateTime CreatedOn
        {
            get => _createdOn;
            set => SetProperty(ref _createdOn, value);
        }

        #endregion
        public void AddValidationRules()
        {
        }
    }
}
