/*
File generated by custom templates
Important: Do not modify this file. Edit the file Choices.cs instead.
*/
#region using directives
using System;
#endregion

namespace Certify.Domain.Entities
{
    [Serializable]
    public abstract class ChoicesBase : BaseEntity
    {
        #region Constructors
        protected ChoicesBase()
        {
        }
        #endregion
        #region Properties

        private Int32 _choiceId;
        public virtual Int32 ChoiceId
        {
            get => _choiceId;
            set => SetProperty(ref _choiceId, value);
        }

        private Int32 _questionId;
        public virtual Int32 QuestionId
        {
            get => _questionId;
            set => SetProperty(ref _questionId, value);
        }

        private string _choiceText;
        public virtual string ChoiceText
        {
            get => _choiceText;
            set => SetProperty(ref _choiceText, value);
        }

        private bool _isCode;
        public virtual bool IsCode
        {
            get => _isCode;
            set => SetProperty(ref _isCode, value);
        }

        private bool _isCorrect;
        public virtual bool IsCorrect
        {
            get => _isCorrect;
            set => SetProperty(ref _isCorrect, value);
        }

        #endregion
        public void AddValidationRules()
        {
        }
    }
}
