/*
File generated by custom templates
Important: Do not modify this file. Edit the file ContactUs.cs instead.
*/
#region using directives
using System;
#endregion

namespace Certify.Domain.Entities
{
    [Serializable]
    public abstract class ContactUsBase : BaseEntity
    {
        #region Constructors
        protected ContactUsBase()
        {
        }
        #endregion
        #region Properties

        private Int32 _contactUsId;
        public virtual Int32 ContactUsId
        {
            get => _contactUsId;
            set => SetProperty(ref _contactUsId, value);
        }

        private string _userName;
        public virtual string UserName
        {
            get => _userName;
            set => SetProperty(ref _userName, value);
        }

        private string _userEmail;
        public virtual string UserEmail
        {
            get => _userEmail;
            set => SetProperty(ref _userEmail, value);
        }

        private string _messageDetail;
        public virtual string MessageDetail
        {
            get => _messageDetail;
            set => SetProperty(ref _messageDetail, value);
        }

        #endregion
        public void AddValidationRules()
        {
        }
    }
}
