/*
File generated by custom templates
Important: Do not modify this file. Edit the file Courses.cs instead.
*/
#region using directives
using System;
#endregion

namespace Certify.Domain.Entities
{
    [Serializable]
    public abstract class CoursesBase : BaseEntity
    {
        #region Constructors
        protected CoursesBase()
        {
        }
        #endregion
        #region Properties

        private Int32 _courseId;
        public virtual Int32 CourseId
        {
            get => _courseId;
            set => SetProperty(ref _courseId, value);
        }

        private string _title;
        public virtual string Title
        {
            get => _title;
            set => SetProperty(ref _title, value);
        }

        private string _description;
        public virtual string Description
        {
            get => _description;
            set => SetProperty(ref _description, value);
        }

        private Int32 _createdBy;
        public virtual Int32 CreatedBy
        {
            get => _createdBy;
            set => SetProperty(ref _createdBy, value);
        }

        private DateTime _createdOn;
        public virtual DateTime CreatedOn
        {
            get => _createdOn;
            set => SetProperty(ref _createdOn, value);
        }

        #endregion
        public void AddValidationRules()
        {
        }
    }
}
