/*
File generated by custom templates
Important: Do not modify this file. Edit the file ExamQuestions.cs instead.
*/
#region using directives
using System;
#endregion

namespace Certify.Domain.Entities
{
    [Serializable]
    public abstract class ExamQuestionsBase : BaseEntity
    {
        #region Constructors
        protected ExamQuestionsBase()
        {
        }
        #endregion
        #region Properties

        private Int32 _examQuestionId;
        public virtual Int32 ExamQuestionId
        {
            get => _examQuestionId;
            set => SetProperty(ref _examQuestionId, value);
        }

        private Int32 _examId;
        public virtual Int32 ExamId
        {
            get => _examId;
            set => SetProperty(ref _examId, value);
        }

        private Int32 _questionId;
        public virtual Int32 QuestionId
        {
            get => _questionId;
            set => SetProperty(ref _questionId, value);
        }

        private Int32? _selectedChoiceId;
        public virtual Int32? SelectedChoiceId
        {
            get => _selectedChoiceId;
            set => SetProperty(ref _selectedChoiceId, value);
        }

        private bool? _isCorrect;
        public virtual bool? IsCorrect
        {
            get => _isCorrect;
            set => SetProperty(ref _isCorrect, value);
        }

        private bool? _reviewLater;
        public virtual bool? ReviewLater
        {
            get => _reviewLater;
            set => SetProperty(ref _reviewLater, value);
        }

        #endregion
        public void AddValidationRules()
        {
        }
    }
}
