/*
File generated by custom templates
Important: Do not modify this file. Edit the file Exams.cs instead.
*/
#region using directives
using System;
#endregion

namespace Certify.Domain.Entities
{
    [Serializable]
    public abstract class ExamsBase : BaseEntity
    {
        #region Constructors
        protected ExamsBase()
        {
        }
        #endregion
        #region Properties

        private Int32 _examId;
        public virtual Int32 ExamId
        {
            get => _examId;
            set => SetProperty(ref _examId, value);
        }

        private Int32 _courseId;
        public virtual Int32 CourseId
        {
            get => _courseId;
            set => SetProperty(ref _courseId, value);
        }

        private Int32 _userId;
        public virtual Int32 UserId
        {
            get => _userId;
            set => SetProperty(ref _userId, value);
        }

        private string _status;
        public virtual string Status
        {
            get => _status;
            set => SetProperty(ref _status, value);
        }

        private DateTime _startedOn;
        public virtual DateTime StartedOn
        {
            get => _startedOn;
            set => SetProperty(ref _startedOn, value);
        }

        private DateTime? _finishedOn;
        public virtual DateTime? FinishedOn
        {
            get => _finishedOn;
            set => SetProperty(ref _finishedOn, value);
        }

        private string _feedback;
        public virtual string Feedback
        {
            get => _feedback;
            set => SetProperty(ref _feedback, value);
        }

        #endregion
        public void AddValidationRules()
        {
        }
    }
}
