/*
File generated by custom templates
Important: Do not modify this file. Edit the file Notification.cs instead.
*/
#region using directives
using System;
#endregion

namespace Certify.Domain.Entities
{
    [Serializable]
    public abstract class NotificationBase : BaseEntity
    {
        #region Constructors
        protected NotificationBase()
        {
            this.IsActive = true;
        }
        #endregion
        #region Properties

        private Int32 _notificationId;
        public virtual Int32 NotificationId
        {
            get => _notificationId;
            set => SetProperty(ref _notificationId, value);
        }

        private string _subject;
        public virtual string Subject
        {
            get => _subject;
            set => SetProperty(ref _subject, value);
        }

        private string _content;
        public virtual string Content
        {
            get => _content;
            set => SetProperty(ref _content, value);
        }

        private DateTime _createdOn;
        public virtual DateTime CreatedOn
        {
            get => _createdOn;
            set => SetProperty(ref _createdOn, value);
        }

        private DateTime _scheduledSendTime;
        public virtual DateTime ScheduledSendTime
        {
            get => _scheduledSendTime;
            set => SetProperty(ref _scheduledSendTime, value);
        }

        private bool _isActive;
        public virtual bool IsActive
        {
            get => _isActive;
            set => SetProperty(ref _isActive, value);
        }

        #endregion
        public void AddValidationRules()
        {
        }
    }
}
