/*
File generated by custom templates
Important: Do not modify this file. Edit the file Questions.cs instead.
*/
#region using directives
using System;
#endregion

namespace Certify.Domain.Entities
{
    [Serializable]
    public abstract class QuestionsBase : BaseEntity
    {
        #region Constructors
        protected QuestionsBase()
        {
        }
        #endregion
        #region Properties

        private Int32 _questionId;
        public virtual Int32 QuestionId
        {
            get => _questionId;
            set => SetProperty(ref _questionId, value);
        }

        private Int32 _courseId;
        public virtual Int32 CourseId
        {
            get => _courseId;
            set => SetProperty(ref _courseId, value);
        }

        private string _questionText;
        public virtual string QuestionText
        {
            get => _questionText;
            set => SetProperty(ref _questionText, value);
        }

        private string _difficultyLevel;
        public virtual string DifficultyLevel
        {
            get => _difficultyLevel;
            set => SetProperty(ref _difficultyLevel, value);
        }

        private bool _isCode;
        public virtual bool IsCode
        {
            get => _isCode;
            set => SetProperty(ref _isCode, value);
        }

        private bool _hasMultipleAnswers;
        public virtual bool HasMultipleAnswers
        {
            get => _hasMultipleAnswers;
            set => SetProperty(ref _hasMultipleAnswers, value);
        }

        #endregion
        public void AddValidationRules()
        {
        }
    }
}
