/*
File generated by custom templates
Important: Do not modify this file. Edit the file Roles.cs instead.
*/
#region using directives
using System;
#endregion

namespace Certify.Domain.Entities
{
    [Serializable]
    public abstract class RolesBase : BaseEntity
    {
        #region Constructors
        protected RolesBase()
        {
        }
        #endregion
        #region Properties

        private Int32 _roleId;
        public virtual Int32 RoleId
        {
            get => _roleId;
            set => SetProperty(ref _roleId, value);
        }

        private string _roleName;
        public virtual string RoleName
        {
            get => _roleName;
            set => SetProperty(ref _roleName, value);
        }

        #endregion
        public void AddValidationRules()
        {
        }
    }
}
