/*
File generated by custom templates
Important: Do not modify this file. Edit the file SmartApp.cs instead.
*/
#region using directives
using System;
#endregion

namespace Certify.Domain.Entities
{
    [Serializable]
    public abstract class SmartAppBase : BaseEntity
    {
        #region Constructors
        protected SmartAppBase()
        {
        }
        #endregion
        #region Properties

        private Int32 _smartAppId;
        public virtual Int32 SmartAppId
        {
            get => _smartAppId;
            set => SetProperty(ref _smartAppId, value);
        }

        private string _appName;
        public virtual string AppName
        {
            get => _appName;
            set => SetProperty(ref _appName, value);
        }

        #endregion
        public void AddValidationRules()
        {
        }
    }
}
