/*
File generated by custom templates
Important: Do not modify this file. Edit the file UserProfile.cs instead.
*/
#region using directives
using System;
#endregion

namespace Certify.Domain.Entities
{
    [Serializable]
    public abstract class UserProfileBase : BaseEntity
    {
        #region Constructors
        protected UserProfileBase()
        {
        }
        #endregion
        #region Properties

        private Int32 _userId;
        public virtual Int32 UserId
        {
            get => _userId;
            set => SetProperty(ref _userId, value);
        }

        private string _displayName;
        public virtual string DisplayName
        {
            get => _displayName;
            set => SetProperty(ref _displayName, value);
        }

        private string _firstName;
        public virtual string FirstName
        {
            get => _firstName;
            set => SetProperty(ref _firstName, value);
        }

        private string _lastName;
        public virtual string LastName
        {
            get => _lastName;
            set => SetProperty(ref _lastName, value);
        }

        private string _email;
        public virtual string Email
        {
            get => _email;
            set => SetProperty(ref _email, value);
        }

        private string _adObjId;
        public virtual string AdObjId
        {
            get => _adObjId;
            set => SetProperty(ref _adObjId, value);
        }

        private string _profileImageUrl;
        public virtual string ProfileImageUrl
        {
            get => _profileImageUrl;
            set => SetProperty(ref _profileImageUrl, value);
        }

        private DateTime _createdOn;
        public virtual DateTime CreatedOn
        {
            get => _createdOn;
            set => SetProperty(ref _createdOn, value);
        }

        #endregion
        public void AddValidationRules()
        {
        }
    }
}
