/*
File generated by custom templates
Important: Do not modify this file. Edit the file UserActivityLog.cs instead.
*/
#region using directives
using System;
#endregion

namespace Certify.Domain.Entities
{
    [Serializable]
    public abstract class UserActivityLogBase : BaseEntity
    {
        #region Constructors
        protected UserActivityLogBase()
        {
        }
        #endregion
        #region Properties

        private Int32 _logId;
        public virtual Int32 LogId
        {
            get => _logId;
            set => SetProperty(ref _logId, value);
        }

        private Int32? _userId;
        public virtual Int32? UserId
        {
            get => _userId;
            set => SetProperty(ref _userId, value);
        }

        private string _activityType;
        public virtual string ActivityType
        {
            get => _activityType;
            set => SetProperty(ref _activityType, value);
        }

        private string _activityDescription;
        public virtual string ActivityDescription
        {
            get => _activityDescription;
            set => SetProperty(ref _activityDescription, value);
        }

        private DateTime _logDate;
        public virtual DateTime LogDate
        {
            get => _logDate;
            set => SetProperty(ref _logDate, value);
        }

        #endregion
        public void AddValidationRules()
        {
        }
    }
}
