/*
File generated by custom templates
Important: Do not modify this file. Edit the file UserNotifications.cs instead.
*/
#region using directives
using System;
#endregion

namespace Certify.Domain.Entities
{
    [Serializable]
    public abstract class UserNotificationsBase : BaseEntity
    {
        #region Constructors
        protected UserNotificationsBase()
        {
        }
        #endregion
        #region Properties

        private Int32 _userNotificationId;
        public virtual Int32 UserNotificationId
        {
            get => _userNotificationId;
            set => SetProperty(ref _userNotificationId, value);
        }

        private Int32 _notificationId;
        public virtual Int32 NotificationId
        {
            get => _notificationId;
            set => SetProperty(ref _notificationId, value);
        }

        private Int32 _userId;
        public virtual Int32 UserId
        {
            get => _userId;
            set => SetProperty(ref _userId, value);
        }

        private string _emailSubject;
        public virtual string EmailSubject
        {
            get => _emailSubject;
            set => SetProperty(ref _emailSubject, value);
        }

        private string _emailContent;
        public virtual string EmailContent
        {
            get => _emailContent;
            set => SetProperty(ref _emailContent, value);
        }

        private bool _notificationSent;
        public virtual bool NotificationSent
        {
            get => _notificationSent;
            set => SetProperty(ref _notificationSent, value);
        }

        private DateTime? _sentOn;
        public virtual DateTime? SentOn
        {
            get => _sentOn;
            set => SetProperty(ref _sentOn, value);
        }

        private DateTime _createdOn;
        public virtual DateTime CreatedOn
        {
            get => _createdOn;
            set => SetProperty(ref _createdOn, value);
        }

        #endregion
        public void AddValidationRules()
        {
        }
    }
}
