/*
File generated by custom templates
*/
#region using directives
using System;
using System.ComponentModel.DataAnnotations;
#endregion

namespace Certify.Domain.Entities
{
    [Serializable]
    public class UserRole : UserRoleBase
    {
        #region Constructors
        public UserRole():base(){}
        #endregion
    }
}
