/*
File generated by custom templates
Important: Do not modify this file. Edit the file UserRole.cs instead.
*/
#region using directives
using System;
#endregion

namespace Certify.Domain.Entities
{
    [Serializable]
    public abstract class UserRoleBase : BaseEntity
    {
        #region Constructors
        protected UserRoleBase()
        {
        }
        #endregion
        #region Properties

        private Int32 _userRoleId;
        public virtual Int32 UserRoleId
        {
            get => _userRoleId;
            set => SetProperty(ref _userRoleId, value);
        }

        private Int32 _roleId;
        public virtual Int32 RoleId
        {
            get => _roleId;
            set => SetProperty(ref _roleId, value);
        }

        private Int32 _userId;
        public virtual Int32 UserId
        {
            get => _userId;
            set => SetProperty(ref _userId, value);
        }

        private Int32 _smartAppId;
        public virtual Int32 SmartAppId
        {
            get => _smartAppId;
            set => SetProperty(ref _smartAppId, value);
        }

        #endregion
        public void AddValidationRules()
        {
        }
    }
}
